SectionVerb {
    EnableSequence [
        cset "name='FRDDR_A SINK 1 SEL' 'OUT 1'"
        cset "name='FRDDR_A SRC 1 EN Switch' on"
        cset "name='TDMOUT_B SRC SEL' 'IN 0'"
        cset "name='TDMOUT_B Gain Enable Switch' off"
        cset "name='TOHDMITX I2S SRC' 'I2S B'"
        cset "name='TOHDMITX Switch' on"
    ]
}
SectionDevice."HDMI" {
    Comment "HDMI stereo"
    Value {
        PlaybackPCM "hw:${CardId},0"
        PlaybackChannels 2
        PlaybackPriority 200
    }
}
