# SPDX-License-Identifier: GPL-2.0-only
# Mali-G31 exposes desktop OpenGL 3.1. Qt Quick effects can use incompatible
# legacy GL operations in that context (KDE bug 486460). Use hardware GLES for
# KWin only; leave application rendering and Mesa's advertised versions alone.
[Service]
Environment=KWIN_COMPOSE=O2ES
